name: Validate maven builds
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  branch_protection_rule:
    types: [created, deleted]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt
      - id: build-maven
        name: Build with Maven
        run: |
          mvn \
            -Dgpg.skip \
            --batch-mode \
            --update-snapshots \
            verify